### ISSUE TITLE
Couldn't read file

### ISSUE THREAD

**Issue by nbanik** [damonge/CUTE#2]
Hi David, 

  I am trying to run CUTE with my data that is in the format RA DEC z, the first few lines of the file looks like this: 

240.691076691   -0.570713581795   0.1943174
244.337480415   -0.429952943145   0.4170079
244.533179409   -0.44337785704   0.4031112
244.770759945   -0.498106983144   0.4358312
245.197502192   -0.479864602544   0.3976909
245.736807492   -0.426961676141   0.4256459
249.521239368   -0.46601278951   0.4227384
237.493807776   -0.0716001579809   0.2745234

When I run cute I got the following error message

Initializing random number generator
First random number : 417175341 
Using 1 threads 

**\* Reading run parameters 
  Using estimator: LS

**\* Setting z-distance relation from the cosmology:
- Omega_M = 0.315 
- Omega_L = 0.685 
- w       = -1.000  

**\* Monopole correlation function: 
- Range: 0.000 < r < 220.000 Mpc/h
- #bins: 50
- Resolution: D(r) = 4.400 Mpc/h
- Using a brute-force approach 

**\* Reading catalog from file /home/nil/Downloads/DR7radecz_data.txt
  30272 lines in the catalog
CUTE: Couldn't read file /home/nil/Downloads/DR7radecz_data.txt, line 1 

I have attached the param file.

[param.txt](https://github.com/damonge/CUTE/files/269331/param.txt)

**Comment by nbanik** [comment]
Ok, I resolved this issue. Turns out I compiled CUTE with -D_WITH_WEIGHTS, so it expects a weight column. So I added a weight column with all the elements =1 and now it works.

**Comment by damonge** [comment]
Ok, thanks for raising this. Maybe I should make CUTE trow a more informative error message.
