### ISSUE TITLE
HAVE_MPI variable in Makefile does not get passed

### ISSUE THREAD

**Issue by bengranett** [damonge/CUTE#4]
There is an issue in CUTE/Makefile that the `_HAVE_MPI` variable is not getting passed when compiling `src/io.c`.  This leads to the MPI_reduce code not getting run and wrong results.

The Makefile runs the following line missing `-D_HAVE_MPI`
```
mpicc -Wall -O3 -D_VERBOSE  -D_HAVE_OMP  -D_WITH_WEIGHTS  -D_LOGBIN -DI_R_MAX=.00666 -DLOG_R_MAX=2.176091259 -DI_THETA_MAX=5.72957 -DLOG_TH_MAX=-.758122630 -DI_RL_MAX=.00666 -DI_RT_MAX=.00666 -DI_R3D_MAX=.00666 -DLOG_R3D_MAX=2.176091259 -D_HISTO_2D_64 -DN_LOGINT=10 -c src/io.c -o src/io.o -I./src -I/home/damonge/include
```

**Comment by damonge** [comment]
Thanks for reporting @bengranett . This should be solved now - please reopen if it isn't.
