### ISSUE TITLE
Bug in io.c

### ISSUE THREAD

**Issue by mcagliari** [damonge/CUTE#9]
Hello,
I am currently using your code CUTE for my work and I would like to ask you a question about the input parameter 'RR_filename', which makes it possible to feed the random catalogue auto-correlation to the program without the need of recomputing it.
In order to use this feature I added to the parameter_file the following line:

`RR_filename = /home/marina/vipers-nn/prova_cf.dat`

where /home/marina/vipers-nn/prova_cf.dat is the output of a previous CUTE with the same random catalogue, binning parameters and correlation function type. However, by running the code with the new parameter_file I got the following error:

```
*** Correlating
 - D-D
Node 0 : 30970 iters, will take from 0 to 30970
    Relative time ellapsed 1497.9 ms
 - D-R
Node 0 : 30970 iters, will take from 0 to 30970
    Relative time ellapsed 3588.9 ms
 - R-R
*** Reading RR from file /home/marina/vipers-nn/prova_cf.dat
CUTE: Couldn't read file /home/marina/vipers-nn/prova_cf.dat, line 1
```

By changing from `w`, write, to `r`, read, at **line 192** of the **io.c** file in the function `read_RR`, the code runs and reads the RR file:

```
*** Correlating
 - D-D
Node 0 : 31254 iters, will take from 0 to 31254
    Relative time ellapsed 1476.0 ms
 - D-R
Node 0 : 31254 iters, will take from 0 to 31254
    Relative time ellapsed 3472.5 ms
 - R-R
*** Reading RR from file /home/marina/vipers-nn/prova_cf.dat

    Relative time ellapsed 1.6 ms

*** Writing output file /home/marina/vipers-nn/prova_cf_wRR.dat

*** Cleaning up
             Done !!!             

```
I just wanted to ask you if I was passing in the wrong way the RR file and so there is no need in making the change in the code, or if the `w` was just a bug.

Thank you!

**Comment by damonge** [comment]
Thanks a lot @mcagliari . This has been solved in #8
